### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by cherold01** [cherold01/SupraglacialStreamsAletsch#1]
- [x] Adjust Filter and jump in stage
- [x] Uncertainty estimates -> Do all calculations in julia
- [x] Statistics Aspect Ratio vs other variables
- [x] Hydraulic friction factors
- [x] Check for nonlinear relations
- [x] Comparison WTW - CTD discharges with differnet sampling time -> are the differences in Q bc of that?
- [x] Histograms Hand measurements
- [x] Try to export gradient / sinuosity around each measurement
- [x] send working title to elias
- [x] change plot points in AR vs sinu etc, one color per stream, one symbol per section
-> think about what causes different "regimes" in Depth-width / AR-width / ... plots
-> investigate Depth-Width correlation
- [x] check photos for different discharges in WTW and CTD
- [x] change WTW time uncertainty to 10s
- [x] think about p values: p-value-fishing lowers significant p-value. is my stream section1, section 2 and average of both ok?
- [ ] validate AR from point survey with discharge measurements and width from GIS 
-> problems with MC measurements error propagation. truncate!
- [x] f @ Qmax from traces df, take Q in a certain timeperiod (where we expect the max) as Qmax
- [ ] calculate data from stream 0
- [ ] optional: curvature per survey point in GIS? 
- [x] Add uncertainty bands to plots & make them more presentable

**Writing ToDos**
- [x] get zotero
- [ ] generate map 
- [x] minor ToDos see red in Latex

**Fix issues:**
- [x] Correct measurments for DeltaH
- [x] 1/Sinuosity
- [ ] _(Take Width and average height for v(s) from GIS)_
